require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GameweeksController do

  # This should return the minimal set of attributes required to create a valid
  # Gameweek. As you add validations to Gameweek, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all gameweeks as @gameweeks" do
      gameweek = Gameweek.create! valid_attributes
      get :index
      assigns(:gameweeks).should eq([gameweek])
    end
  end

  describe "GET show" do
    it "assigns the requested gameweek as @gameweek" do
      gameweek = Gameweek.create! valid_attributes
      get :show, :id => gameweek.id.to_s
      assigns(:gameweek).should eq(gameweek)
    end
  end

  describe "GET new" do
    it "assigns a new gameweek as @gameweek" do
      get :new
      assigns(:gameweek).should be_a_new(Gameweek)
    end
  end

  describe "GET edit" do
    it "assigns the requested gameweek as @gameweek" do
      gameweek = Gameweek.create! valid_attributes
      get :edit, :id => gameweek.id.to_s
      assigns(:gameweek).should eq(gameweek)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Gameweek" do
        expect {
          post :create, :gameweek => valid_attributes
        }.to change(Gameweek, :count).by(1)
      end

      it "assigns a newly created gameweek as @gameweek" do
        post :create, :gameweek => valid_attributes
        assigns(:gameweek).should be_a(Gameweek)
        assigns(:gameweek).should be_persisted
      end

      it "redirects to the created gameweek" do
        post :create, :gameweek => valid_attributes
        response.should redirect_to(Gameweek.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gameweek as @gameweek" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gameweek.any_instance.stub(:save).and_return(false)
        post :create, :gameweek => {}
        assigns(:gameweek).should be_a_new(Gameweek)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gameweek.any_instance.stub(:save).and_return(false)
        post :create, :gameweek => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested gameweek" do
        gameweek = Gameweek.create! valid_attributes
        # Assuming there are no other gameweeks in the database, this
        # specifies that the Gameweek created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Gameweek.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => gameweek.id, :gameweek => {'these' => 'params'}
      end

      it "assigns the requested gameweek as @gameweek" do
        gameweek = Gameweek.create! valid_attributes
        put :update, :id => gameweek.id, :gameweek => valid_attributes
        assigns(:gameweek).should eq(gameweek)
      end

      it "redirects to the gameweek" do
        gameweek = Gameweek.create! valid_attributes
        put :update, :id => gameweek.id, :gameweek => valid_attributes
        response.should redirect_to(gameweek)
      end
    end

    describe "with invalid params" do
      it "assigns the gameweek as @gameweek" do
        gameweek = Gameweek.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gameweek.any_instance.stub(:save).and_return(false)
        put :update, :id => gameweek.id.to_s, :gameweek => {}
        assigns(:gameweek).should eq(gameweek)
      end

      it "re-renders the 'edit' template" do
        gameweek = Gameweek.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gameweek.any_instance.stub(:save).and_return(false)
        put :update, :id => gameweek.id.to_s, :gameweek => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gameweek" do
      gameweek = Gameweek.create! valid_attributes
      expect {
        delete :destroy, :id => gameweek.id.to_s
      }.to change(Gameweek, :count).by(-1)
    end

    it "redirects to the gameweeks list" do
      gameweek = Gameweek.create! valid_attributes
      delete :destroy, :id => gameweek.id.to_s
      response.should redirect_to(gameweeks_url)
    end
  end

end
