require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PicksController do

  # This should return the minimal set of attributes required to create a valid
  # Pick. As you add validations to Pick, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all picks as @picks" do
      pick = Pick.create! valid_attributes
      get :index
      assigns(:picks).should eq([pick])
    end
  end

  describe "GET show" do
    it "assigns the requested pick as @pick" do
      pick = Pick.create! valid_attributes
      get :show, :id => pick.id.to_s
      assigns(:pick).should eq(pick)
    end
  end

  describe "GET new" do
    it "assigns a new pick as @pick" do
      get :new
      assigns(:pick).should be_a_new(Pick)
    end
  end

  describe "GET edit" do
    it "assigns the requested pick as @pick" do
      pick = Pick.create! valid_attributes
      get :edit, :id => pick.id.to_s
      assigns(:pick).should eq(pick)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pick" do
        expect {
          post :create, :pick => valid_attributes
        }.to change(Pick, :count).by(1)
      end

      it "assigns a newly created pick as @pick" do
        post :create, :pick => valid_attributes
        assigns(:pick).should be_a(Pick)
        assigns(:pick).should be_persisted
      end

      it "redirects to the created pick" do
        post :create, :pick => valid_attributes
        response.should redirect_to(Pick.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pick as @pick" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pick.any_instance.stub(:save).and_return(false)
        post :create, :pick => {}
        assigns(:pick).should be_a_new(Pick)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pick.any_instance.stub(:save).and_return(false)
        post :create, :pick => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pick" do
        pick = Pick.create! valid_attributes
        # Assuming there are no other picks in the database, this
        # specifies that the Pick created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pick.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => pick.id, :pick => {'these' => 'params'}
      end

      it "assigns the requested pick as @pick" do
        pick = Pick.create! valid_attributes
        put :update, :id => pick.id, :pick => valid_attributes
        assigns(:pick).should eq(pick)
      end

      it "redirects to the pick" do
        pick = Pick.create! valid_attributes
        put :update, :id => pick.id, :pick => valid_attributes
        response.should redirect_to(pick)
      end
    end

    describe "with invalid params" do
      it "assigns the pick as @pick" do
        pick = Pick.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pick.any_instance.stub(:save).and_return(false)
        put :update, :id => pick.id.to_s, :pick => {}
        assigns(:pick).should eq(pick)
      end

      it "re-renders the 'edit' template" do
        pick = Pick.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pick.any_instance.stub(:save).and_return(false)
        put :update, :id => pick.id.to_s, :pick => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pick" do
      pick = Pick.create! valid_attributes
      expect {
        delete :destroy, :id => pick.id.to_s
      }.to change(Pick, :count).by(-1)
    end

    it "redirects to the picks list" do
      pick = Pick.create! valid_attributes
      delete :destroy, :id => pick.id.to_s
      response.should redirect_to(picks_url)
    end
  end

end
